### ISSUE TITLE
编译缺少文件

### ISSUE THREAD

**Issue by myie9** [zhangkn/TextView4HyperLink#1]
error: Build input file cannot be found: '/Volumes/MACDATA/devops/CRM_outer/QCT.ERP.ios/retail/retail/retail/other/extension/UIBarButtonItem+Extension.m' (in target 'iUIPageControlFix4iOS14' from project 'iUIPageControlFix4iOS14')

**Comment by zhangkn** [comment]
我看下

**Comment by zhangkn** [comment]
> error: Build input file cannot be found: '/Volumes/MACDATA/devops/CRM_outer/QCT.ERP.ios/retail/retail/retail/other/extension/UIBarButtonItem+Extension.m' (in target 'iUIPageControlFix4iOS14' from project 'iUIPageControlFix4iOS14')

我搜索GitHub的项目发现工程有UIBarButtonItem+Extension.m，你只要重新引用下即可

**Comment by zhangkn** [comment]
> UIBarButtonItem+Extension.m
或者你更新最新版本，我修复了

**Comment by zhangkn** [comment]
> error: Build input file cannot be found: '/Volumes/MACDATA/devops/CRM_outer/QCT.ERP.ios/retail/retail/retail/other/extension/UIBarButtonItem+Extension.m' (in target 'iUIPageControlFix4iOS14' from project 'iUIPageControlFix4iOS14')

 已经修复 修复版本为：1598150c0dba4736f29d412280b38e9e8b54157d。 感谢反馈
